project      = "terraform-learn-369718"
#credentials  = "path to service account key json file"
region       = "us-central1"
zone         = "us-central1-a"
machine_type = "f1-micro"
image        = "debian-cloud/debian-11"
